---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: quarterly
    groups:
      dependencies:
        patterns:
          - '*'

  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: quarterly
    groups:
      dependencies:
        patterns:
          - '*'

  - package-ecosystem: uv
    directory: /
    schedule:
      interval: monthly
    groups:
      dependencies:
        patterns:
          - '*'
      test-dependencies:
        patterns:
          - "covdefaults"
          - "coverage"
          - "pytest"
          - "pytest-*"
          - "sybil"
      dev-dependencies:
        patterns:
          - "codespell"
          - "docstrfmt"
          - "mypy"
          - "pre-commit"
          - "pre-commit-hooks"
          - "ruff"
          - "yamllint"
      docs-dependencies:
        patterns:
          - "sphinx"
          - "sphinx-*"
          - "sphinxcontrib-*"
  - package-ecosystem: cargo
    directory: /integration_tests/rmodbus
    schedule:
      interval: quarterly
    groups:
      dependencies:
        patterns:
          - '*'

  - package-ecosystem: cargo
    directory: /integration_tests/tokio
    schedule:
      interval: quarterly
    groups:
      dependencies:
        patterns:
          - '*'
