---
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    # Use uv to speed up the build
    # https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-uv
    pre_create_environment:
      - asdf plugin add uv
      - asdf install uv 0.8.23
      - asdf global uv 0.8.23
    create_environment:
      # Create a virtual environment in '.venv/' folder
      # which is picked up automatically by `uv sync` and `uv run` commands below
      - uv venv "${READTHEDOCS_VIRTUALENV_PATH}"
    install:
      - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv sync --all-extras --group docs
    build:
      html:
        - >
          UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}"
          uv run sphinx-build -T -W --keep-going -b html
          -d _build/doctrees
          -D language=en
          docs/source
          $READTHEDOCS_OUTPUT/html
          -w sphinx.log
          || (cat sphinx.log && exit 1)
