---
name: "Feature Request"
description: "Suggest an idea or feature"
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: "Problem/Motivation"
      description: "Why the feature is needed."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Proposed solution"
      description: "Describe the solution you would like."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Additional context"
      description: >
        Add any other context or screenshots about the feature request here.
    validations:
      required: false
