---
name: Publish to PyPI

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

permissions:
  attestations: write
  contents: write
  id-token: write

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: hynek/build-and-inspect-python-package@v2
        with:
          attest-build-provenance-github: "true"

  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    needs: build
    environment: pypi
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: Release ${{ github.ref }}
