---
name: Typing

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  DEFAULT_PYTHON: "3.12"

jobs:
  mypy:
    name: mypy
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: 🏗 Set up uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
        with:
          enable-cache: true
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: 🏗 Install dependencies
        run: uv sync --all-extras --frozen --dev
      - name: 🚀 Run mypy
        run: uv run mypy examples src tests
